defaults:
  - dataset@features

features:
  type: stft_phase # cross_spectral_phase | stft | stft_phase | stft_mag | stft_real
  n_dft: 1024
  hop_size: 512
  window: hann
  onesided_dft: true
  pad_fft_pow2: true
  n_gcc_phat_bins: 200 # Only select central bins as in https://ieeexplore.ieee.org/document/8461267
  srp_thickness: 10

  class: gnn_ssl.feature_extractors.FeatureExtractor